### ISSUE TITLE
Offset lengths and text sentences missmatches

### ISSUE THREAD

**Issue by afergadis** [WING-NUS/scisumm-corpus#13]
I spotted some lines in the training data where the citation or reference offset have less ids that the ones in citation or reference text.

These are:

| File               | Line | Error                                                                                               |
|--------------------|:----:|-----------------------------------------------------------------------------------------------------|
| C02-1025.ann.txt   |  34  | Reference offset has **two** ids. Reference text has **three** sentences.                           |
| P98-1046.ann.txt   |  19  | Citation offset has **one** id. Citation text has **two** sentences.                                 |
| P98-1046.ann.txt   |  28  | Reference offset has **two** ids. Reference text has **three** sentences, one of them with *sid=0*. |
| P07-1040.annv3.txt |  25  | Reference offset has **one** id. Reference text has **two** sentences.                              |
| I05-5011.ann.txt   | 16   | Reference offset has **one** id. Reference text has **two** sentences.                              |
| P98-2143.ann.txt   | 49   | Reference offset has **three** id. Reference text has **four** sentences.                           |

**Comment by cmkumar87** [comment]
thanks for reporting this issue. We will look at it this week. Would you be able to fix and raise a PR if we confirm the issue? thanks!

**Comment by dennlinger** [comment]
Sorry to reopen this, I was just having a look at the relevant data points and this issue today. In fact, I could confirm not only these, but several more issues (mostly with the citation offsets), which I'm happy to contribute in another PR soon.

**Comment by cmkumar87** [comment]
Could you please open a new issue that you own? This is dated. We didn't get any PR from the original issue owner.
