### ISSUE TITLE
Pre defined facets?

### ISSUE THREAD

**Issue by Saichethan** [WING-NUS/scisumm-corpus#18]
Hello 

Where are predefined facets defined? Bcz different papers has different section names and different number of sections

**Comment by cmkumar87** [comment]
Hi, are you looking for discourse facets? There are available in the annotation files. In this annotation file, for example, https://github.com/WING-NUS/scisumm-corpus/blob/master/data/Training-Set-2019/Task1/From-Training-Set-2018/C00-2123/annotation/C00-2123.ann.txt the last but one column (before the Annotator Name) is the discourse facet.
