### ISSUE TITLE
Which python version is used for evaluation?

### ISSUE THREAD

**Issue by dennlinger** [WING-NUS/scisumm-corpus#21]
Hi,
as per the discussion in the PR #20 , I wanted to ask which exact python version was used to run the evaluation. Or if there is any way to send the required packages in a `requirements.txt`? Even after careful debugging of the output messages, we're not getting the same results as PR #20, even when using their branch for replication.

Our local version is Python 2.7.17, as we determined that Python3 cannot be used here (some lines in the script have python3-incompatible syntax). Can you confirm this is the correct result?

**Comment by cmkumar87** [comment]
Please do not use Python 3. And please do not change the script to make it run. If the script doesn't run it is highly likely that your directory structure of inputs is incorrect.  

Now re result: IITBH-IITP's evaluation was run by their team. So please direct your question to them CCing me, the organiser  . 

Thanks!

**Comment by Saichethan** [comment]
@dennlinger we used python(2.7) worked fine for us

**Comment by dennlinger** [comment]
Sorry for the confusion, as @cmkumar87 already mentioned, it seemed that we had an incorrect folder structure, which the MR by @Saichethan seems to correctly implement (thanks for the pointers again!). #22 now contains a working implementation for our team.
