### ISSUE TITLE
Does ScisummNet have source code?

### ISSUE THREAD

**Issue by JaniceXiong** [WING-NUS/scisumm-corpus#34]
I download the SciSummNet data from the project website, but I wonder if the code or pretrain model of it can be open?

**Comment by cmkumar87** [comment]
Hi Janice, thanks for downloading scisumm! We dont offer a pretrained model. This is a good suggestion. Other people have used CL-SciSumm to develop pretrained models e.g., https://link.springer.com/article/10.1007/s11192-020-03455-z.  I can perhaps ask if any of them would like to share their pretrained models. You may also write to them directly.
Code: We provide evaluation scripts; https://github.com/WING-NUS/scisumm-corpus/tree/master/2018-evaluation-script. The script has the ability to parse our annotation files and your system output files; they can also compute the final scores. 
What other code do you think is helpful for you?
