### ISSUE TITLE
Access to dataset

### ISSUE THREAD

**Issue by msmets** [WING-NUS/scisumm-corpus#35]
Hi,

I am doing my master thesis at KU Leuven in the subject "Scientific paper summarization using deep learning methods". Is it possible to get access to the Laysum dataset? I already contacted Mrs. de Waard but did not get a response yet.

Thanks in advance!

Kind regards,

Michiel

**Comment by knmnyn** [comment]
Sorry, the LaySumm corpus is only available through Elsevier.  IT is not a part of the CL-SciSumm corpus.  You'll have to direct your queries to the maintainer of that corpus.
