### ISSUE TITLE
CL-SciSumm Test Sets for 2019, 2020

### ISSUE THREAD

**Issue by alkakhurana** [WING-NUS/scisumm-corpus#36]
Hi,

Where can I find the test sets for the CL-SciSumm Shared Task 2019 and 2020 in this repository?
Are the documents same as used for CL-SciSumm Shared Task 2018?

Thanks
Alka Khurana

**Comment by cmkumar87** [comment]
https://github.com/WING-NUS/scisumm-corpus/tree/master/data/Test-Set-2018-Gold is the test set for 2018, 2019 and 2020.
